### ISSUE TITLE
フリマアプリ挙動確認

### ISSUE THREAD

**Issue by akiramenowaruiotoko** [akiramenowaruiotoko/furima-31106#9]
#URL
https://furima-31106.herokuapp.com/

Basic認証のID： admin
Basic認証のパスワード：2222
出品者用のメールアドレス : aaa@gmail.com
出品者用のパスワード : aaa111
購入者用のメールアドレス : bbb@gmail.com
購入者用のパスワード : bbb222
購入用カードの番号 : 4242424242424242
期限 : 3月　24年
セキュリティコード : 123

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by akiramenowaruiotoko** [comment]
ご確認とLGTM頂き有り難う御座いました。
